name: "Build"
on:
  push:
    branches:
      - main
      - develop
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - run: nix-build
    - run: nix-shell --run "cdktf synth"