name: "Build"
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Git Checkout"
      uses: actions/checkout@v4
    - name: "Install Nix"
      uses: DeterminateSystems/nix-installer-action@v9
    - name: "Nix Cache"
      uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: "Build Nix Environment"
      run: nix-build
    - name: "CDK TF Synthesize"
      run: nix-shell --run "cdktf synth"
    - name: "Archive CDK TF artifacts"
      uses: actions/upload-artifact@v4
      with:
        name: cdktf-artifacts
        path: cdktf.out