name: "Build"
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    container: abelmokadem/cdktf-python:1
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4
      - name: "Install Requirements"
        run: nix-shell --run "pip install -r requirements"
      - name: "CDK TF Synthesize"
        run: nix-shell --run "cdktf synth"
      - name: "Archive CDK TF artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: cdktf-artifacts
          path: cdktf.out
  diff_acceptance:
    runs-on: ubuntu-latest
    container: abelmokadem/cdktf-python:1
    needs: [ build ]
    steps:
      - name: "Download CDK TF artifacts"
        uses: actions/download-artifact@v4
        with:
          name: cdktf-artifacts
      - name: "Deploy acceptance stack"
        run: nix-shell --run "cdktf diff --skip-synth staging-hello-world-stack"

